name: CTAN upload

inputs:
  filename:
    required: true
  dry-run:
    required: true
  uploader:
    required: true
  email:
    required: true
  version:
    required: false
    default: ${{ github.ref_name }}

runs:
  using: composite
  steps:
    - name: Send to CTAN
      uses: zauguin/ctan-upload@v0.1
      with:
        package-name: luaotfload
        version: ${{ inputs.version }}
        author: '... as before ...'
        uploader: ${{ inputs.uploader }}
        email: ${{ inputs.email }}
        license: gpl2
        summary: "OpenType ‘loader’ for Plain TeX and LaTeX"
        ctan-path: /macros/luatex/generic/luaotfload
        support: https://github.com/latex3/luaotfload/issues
        update: true
        topic: font-use,luatex
        description: |
          The package adopts the TrueType/OpenType Font loader code provided in ConTeXt,
          and adapts it to use in Plain TeX and LaTeX. It works under LuaLaTeX only.
        filename: ${{ inputs.filename }}
        dry-run: ${{ inputs.dry-run }}
        announcement-filename: ctan.ann
