language: generic


sudo: required
services: docker
dist: bionic

install:
  - sudo apt-get install python3-docutils
  - source texlive.sh


cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive


script: 
  - l3build ctan -H --show-log-on-error

deploy:
  - provider: releases
    api_key:
      secure: WWrChLn5LAThh6ay2sZcNkmzyWlV9uvjfGOCg0t/VA/AjEifwIaKN3qFOF55aILUSZ81SDbMtPZXTCywIVjjZY6Pc1I3c9mViWnBSbKLrQe4Z03RdxUosn3K3fPnDZB+8lxs9r02jW8T9bCIwTNe1Bi3Sf4PqoHRpslrqDemxC6lqDn/RHWZYg5ZKL5Md9P8qHQ2Jq9Cil5RRNHgy+jleeko47JrTxWjdi+ULM1SRNZm7mJqUVI3Ko7JvaUOcWsPB4eyTVpR7hONe3/RNnd4ToO7Sh1N3/Ynz2+o+1rBJWfcxR3A8E4wcZgWsTozfCF3Mu7HU9nwdjjmxWDYx5opru1wORmeLyof61B8HOmJVdLikHKGKcwFCz7cBXwcHIhdzVYT7I772JZJfioPQFSuDDljomByaY9r3ubKsHKcvex60bNXwnmk9yHRaNDLB/9ozV8io+LVrZVYZCQHc15jxlmQIElmrhrv1SgPwiabJnESsoHsEPkI0w4zd8Hx7ngk2r79UR3pAqFHEVG1i6y/8TlFRxxOLmVaUBab3gl1QGKnzl4pNVhQwUWXV/1n1fdgl4t4eHBnNY2wc+MYp4eRThnRuo73hQt8wBEYEh8N7uAkP6p6q2xr7pAuGWALRQ5HLIgKlQZA4qyoWaNDa+ZX2AsvbVtzv06BN0GcYIhFoRY=
    file_glob: true
    file:
      - build/distrib/ctan/*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG == *-dev
    prerelease: true
    draft: true
  - provider: releases
    api_key:
      secure: WWrChLn5LAThh6ay2sZcNkmzyWlV9uvjfGOCg0t/VA/AjEifwIaKN3qFOF55aILUSZ81SDbMtPZXTCywIVjjZY6Pc1I3c9mViWnBSbKLrQe4Z03RdxUosn3K3fPnDZB+8lxs9r02jW8T9bCIwTNe1Bi3Sf4PqoHRpslrqDemxC6lqDn/RHWZYg5ZKL5Md9P8qHQ2Jq9Cil5RRNHgy+jleeko47JrTxWjdi+ULM1SRNZm7mJqUVI3Ko7JvaUOcWsPB4eyTVpR7hONe3/RNnd4ToO7Sh1N3/Ynz2+o+1rBJWfcxR3A8E4wcZgWsTozfCF3Mu7HU9nwdjjmxWDYx5opru1wORmeLyof61B8HOmJVdLikHKGKcwFCz7cBXwcHIhdzVYT7I772JZJfioPQFSuDDljomByaY9r3ubKsHKcvex60bNXwnmk9yHRaNDLB/9ozV8io+LVrZVYZCQHc15jxlmQIElmrhrv1SgPwiabJnESsoHsEPkI0w4zd8Hx7ngk2r79UR3pAqFHEVG1i6y/8TlFRxxOLmVaUBab3gl1QGKnzl4pNVhQwUWXV/1n1fdgl4t4eHBnNY2wc+MYp4eRThnRuo73hQt8wBEYEh8N7uAkP6p6q2xr7pAuGWALRQ5HLIgKlQZA4qyoWaNDa+ZX2AsvbVtzv06BN0GcYIhFoRY=
    file_glob: true
    file:
      - build/distrib/ctan/*.zip
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG != *-dev
    prerelease: false
    draft: true
