language: generic


sudo: required
services: docker

install:
 - source texlive.sh


cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive


script: 
  - l3build check -H || ( cat build/*/`ls -t  build/*/*.log | head -n1 | xargs basename | cut -f 1 -d . `.log && false )

