name: Deployment

# Currently we run in two situations:
on:
  # Only triggers for new tags
  push:
    tags: "*"

jobs:
  # Mostly the same as the main.yaml workflow, but we only use a single job
  l3build:
    runs-on: ubuntu-20.04
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v4
      - run: sudo apt-get install python3-docutils
      - name: Install TeX Live
        uses: zauguin/install-texlive@v3
        with:
          # Here we use the same list of packages as in the testing workflow.
          package_file: .github/tl_packages
      - name: Run l3build
        run: l3build ctan -H --show-log-on-error
      - name: Create GitHub release
        uses: ncipollo/release-action@2c591bcc8ecdcd2db72b97d6147f871fcd833ba5
        id: release
        with:
          artifacts: "build/distrib/ctan/*.zip"
          prerelease: ${{ endsWith(github.ref, '-dev') }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # If a test failed, we already notified in the other workflow. Here we notify
      # when a release has been created.
      - name: Send mail
        uses: dawidd6/action-send-mail@4226df7daafa6fc901a43789c49bf7ab309066e7
        with:
          # Currently using my (Marcel's) mail server for sending mails.
          server_address: typesetting.eu
          server_port: 587
          # These values can be changed in the repository settings.
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # If we want to send notifications to additional addresses, add them here as
          # a comma separated list.
          to: latex3-commits@tug.org
          # The name is arbitrary, but if you want to change the address you need to
          # coordinate it with the administrator of the mail server to allow the account
          # to send from the mail address.
          from: LaTeX CI <github@latex-project.org>
          # Determine the subject and body of the mail.
          subject: "New release for ${{github.repository}}: ${{github.ref_name}}"
          body: |
            The release ${{github.ref_name}} has been created for ${{github.repository}}.

            More information can be found at
            ${{steps.release.outputs.html_url}}
