name: Deployment

# Currently we run in two situations:
on:
  # Only triggers for new tags
  push:
    tags: "*"

jobs:
  # Mostly the same as the main.yaml workflow, but we only use a single job
  l3build:
    runs-on: ubuntu-20.04
    steps:
      # Boilerplate
      - name: Checkout repository
        uses: actions/checkout@v2
      # GitHub Actions don't regenerate the test if the key doesn't change, so
      # we integrate a random UUID into the key to keep them different.
      # DO NOT CHANGE THIS
      - name: Generate unique ID
        id: get-id
        run: |
          echo -n ::set-output name=id::
          cat /proc/sys/kernel/random/uuid
      # Actually load the cache. Since we never reuse the key, we need restore-keys
      # to indicate the prefix of our caches. This loads the newest cache with this
      # prefix in the key.
      #
      # If we want to force regeneration of the cache, increase the number after
      # *both* instances of "texlive-v"
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: ~/texlive
          key: texlive-v0-tl2022-${{ steps.get-id.outputs.id }}
          restore-keys: texlive-v0-
      # We need docutils for our documentation
      - run: sudo apt-get install python3-docutils
      - name: Install TeX Live
        uses: zauguin/install-texlive@main
        with:
          # Here we use the same list of packages as in the testing workflow.
          package_file: .github/tl_packages
      - name: Run l3build
        run: l3build ctan -H --show-log-on-error
      - name: Create GitHub release
        uses: ncipollo/release-action@880be3d0a71bc0fa98db60201d2cbdc27324f547
        id: release
        with:
          artifacts: "build/distrib/ctan/*.zip"
          prerelease: ${{ endsWith(github.ref, '-dev') }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # To get the name of the release, we need to remove a prefix from a variable.
      # Sadly, this isn't supported by GitHub's *extremely* limited expression syntax
      # and we have to use a separate action instead.
      #
      - name: Get name
        uses: frabert/replace-string-action@9b62dfe3ae936b1cc380f2421c8ac9e63a4a3e85
        id: name
        with:
          pattern: "^refs/tags/"
          string: ${{ github.ref }}
          replace-with: ""
      # If a test failed, we already notified in the other workflow. Here we notify
      # when a release has been created.
      - name: Send mail
        uses: dawidd6/action-send-mail@ceb614a2c5737d913f2d2729e2bcc70ad933382b
        with:
          # Currently using my (Marcel's) mail server for sending mails.
          server_address: typesetting.eu
          server_port: 587
          # These values can be changed in the repository settings.
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # If we want to send notifications to additional addresses, add them here as
          # a comma separated list.
          to: latex3-commits@tug.org
          # The name is arbitrary, but if you want to change the address you need to
          # coordinate it with the administrator of the mail server to allow the account
          # to send from the mail address.
          from: LaTeX CI <github@latex-project.org>
          # Determine the subject and body of the mail.
          subject: "New release for ${{github.repository}}: ${{steps.name.outputs.replaced}}"
          body: |
            The release ${{steps.name.outputs.replaced}} has been created for ${{github.repository}}.

            More information can be found at
            ${{steps.release.outputs.html_url}}
